#version: '3.8' ccc

services:
  app:
    build: ./backend
    image: exercise-laravel-app
    container_name: exercise-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
    networks:
      - exercise-network

  nginx:
    image: nginx:alpine
    container_name: exercise-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - exercise-network        

  db:
    platform: ${DOCKER_MYSQL_PLATFORM} #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    image: mysql:8.0
    container_name: exercise-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - exercise-network
    ports:
      - "3306:3306"

  node:
    platform: ${DOCKER_NODE_PLATFORM} #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build: ./frontend
    image: exercise-node
    container_name: exercise-node
    ports:
      - "3000:3000"
    restart: 'no'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - exercise-network

networks:
  exercise-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
